version: '3'

services:

  app:
    build: .
    container_name: micro01-app
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - _DB_HOST=db
      - _DB_DATABASE=micro01
      - _DB_USERNAME=root
      - _DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build: .docker/nginx
    container_name: micro01-nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    build: ./.docker/mysql
    container_name: micro01-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=micro01
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
